"""Added sent_back field to inference results

Revision ID: 15906d5588d2
Revises: f03ac80a5241
Create Date: 2024-04-03 16:19:12.427427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15906d5588d2'
down_revision = 'f03ac80a5241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inference_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_back', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inference_results', schema=None) as batch_op:
        batch_op.drop_column('sent_back')

    # ### end Alembic commands ###
