"""Initial migration

Revision ID: 574daf9df370
Revises: 
Create Date: 2024-03-20 15:13:03.014769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574daf9df370'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sleap_neural_network',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('network_folder_path', sa.String(), nullable=False),
    sa.Column('currently_training', sa.Boolean(), nullable=False),
    sa.Column('celery_training_task_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('inference_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('results_json', sa.String(), nullable=True),
    sa.Column('network_uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['network_uid'], ['sleap_neural_network.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inference_results')
    op.drop_table('sleap_neural_network')
    # ### end Alembic commands ###
