"""Added datetime and file information fields into InferenceResults model

Revision ID: f03ac80a5241
Revises: 97cc999e7c8a
Create Date: 2024-04-02 21:27:49.749842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03ac80a5241'
down_revision = '97cc999e7c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inference_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_inference_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('finished_inference_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('currently_running_inference', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('video_base64', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('file_name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inference_results', schema=None) as batch_op:
        batch_op.drop_column('file_name')
        batch_op.drop_column('video_base64')
        batch_op.drop_column('currently_running_inference')
        batch_op.drop_column('finished_inference_at')
        batch_op.drop_column('started_inference_at')

    # ### end Alembic commands ###
